import Vue from 'vue'
import { Button ,Upload,Steps,Checkbox,CheckboxGroup,Step,Tabs,TabPane,Cascader,Select,Alert,Option,Tree,Form,FormItem,Input,Message,Container,Tag,Header,Aside,Main,MessageBox ,Menu,Submenu,MenuItemGroup,MenuItem,Breadcrumb,BreadcrumbItem,Dialog,Card,Row,Col,Table,TableColumn,Pagination,Switch,Tooltip} from 'element-ui'


import Timeline from './timeline/index.js'
import TimelineItem from './timeline-item/index.js'
Vue.use(Timeline)
Vue.use(TimelineItem)
Vue.use(Button)
Vue.use(Upload)
Vue.use(Form)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(FormItem)
Vue.use(Step)
Vue.use(Steps)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(TabPane)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Switch)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.use(Tag)
Vue.use(Tree)
Vue.use(Select)
Vue.use(Option)
Vue.use(Cascader)
Vue.use(Alert)
Vue.use(Tabs)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
